/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAssistantsRouteImport } from './routes/_authed/assistants'
import { Route as AuthedModelsRouteImport } from './routes/_authed/models'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as AuthedCIdRouteImport } from './routes/_authed/c.$id'
import { Route as ApiAttachmentsIdRouteImport } from './routes/api/attachments.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAssistantsRoute = AuthedAssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedModelsRoute = AuthedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCIdRoute = AuthedCIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAttachmentsIdRoute = ApiAttachmentsIdRouteImport.update({
  id: '/api/attachments/$id',
  path: '/api/attachments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/assistants': typeof AuthedAssistantsRoute
  '/models': typeof AuthedModelsRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/models': typeof ApiModelsRoute
  '/api/status': typeof ApiStatusRoute
  '/c/$id': typeof AuthedCIdRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/assistants': typeof AuthedAssistantsRoute
  '/models': typeof AuthedModelsRoute
  '/settings': typeof AuthedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/models': typeof ApiModelsRoute
  '/api/status': typeof ApiStatusRoute
  '/': typeof AuthedIndexRoute
  '/c/$id': typeof AuthedCIdRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_authed/assistants': typeof AuthedAssistantsRoute
  '/_authed/models': typeof AuthedModelsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/models': typeof ApiModelsRoute
  '/api/status': typeof ApiStatusRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/c/$id': typeof AuthedCIdRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/assistants'
    | '/models'
    | '/settings'
    | '/api/chat'
    | '/api/models'
    | '/api/status'
    | '/c/$id'
    | '/api/attachments/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/assistants'
    | '/models'
    | '/settings'
    | '/api/chat'
    | '/api/models'
    | '/api/status'
    | '/'
    | '/c/$id'
    | '/api/attachments/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/_authed/assistants'
    | '/_authed/models'
    | '/_authed/settings'
    | '/api/chat'
    | '/api/models'
    | '/api/status'
    | '/_authed/'
    | '/_authed/c/$id'
    | '/api/attachments/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiAttachmentsIdRoute: typeof ApiAttachmentsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assistants': {
      id: '/_authed/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AuthedAssistantsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/models': {
      id: '/_authed/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthedModelsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/c/$id': {
      id: '/_authed/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof AuthedCIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/attachments/$id': {
      id: '/api/attachments/$id'
      path: '/api/attachments/$id'
      fullPath: '/api/attachments/$id'
      preLoaderRoute: typeof ApiAttachmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedAssistantsRoute: typeof AuthedAssistantsRoute
  AuthedModelsRoute: typeof AuthedModelsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCIdRoute: typeof AuthedCIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAssistantsRoute: AuthedAssistantsRoute,
  AuthedModelsRoute: AuthedModelsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCIdRoute: AuthedCIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiAttachmentsIdRoute: ApiAttachmentsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
